### ISSUE TITLE
[EDI] Handle (or ignore?) line endings

### ISSUE THREAD

**Issue by DGollings** [jf-tech/omniparser#117]
Consider the header

`UNA:+.? '`

This wouldn't be

```
    "component_delimiter": ":",
    "element_delimiter": "+",
    "segment_delimiter": "'",
    "release_character": "?",
```

But instead is 
```
    "component_delimiter": ":",
    "element_delimiter": "+",
    "segment_delimiter": "'\n", <--
    "release_character": "?",
```
If the file you're trying to read contains line endings. Maybe the safest/easiest option would be removing all line endings?

**Comment by jf-tech** [comment]
@DGollings not sure I understand, you're saying if the input EDI file has a header indicating segment delimiter is `'` but somehow the rest of the file is filled with `\n`?

Generally speaking, EDI standard is pretty strict, I would normally say in this situation the input EDI file is invalid/corrupted. If you have a real case where the supplier of the EDI file doesn't want to change (some businesses are stubborn about their "incorrectness") then we can consider adding a boolean flag in `file_declaration` section for edi schema: `remove_cr_lf`.

what do you think?

**Comment by DGollings** [comment]
No, the entire file is ' _and_ \n

Which tbh is pretty legible are you sure ignoring line endings isn't part of the spec? If I do an online image search for' edifact example' I see plenty of similar looking headers and one line per segment examples

**Comment by jf-tech** [comment]
In this situation I would simply use `'\n` as seg delim

**Comment by DGollings** [comment]
Sure, but I'd consider mentioning it somewhere. Took me quite some time to figure out :)

**Comment by jf-tech** [comment]
Okay I dug around there is not definitive answer that i am aware of. IBM/Oracle/MSFT all have some minor different implementation. But I would use this MSDN page for future reference: https://docs.microsoft.com/en-sg/troubleshoot/biztalk/segment-terminator-x12-encoded-interchange. Basically it allows a single char seg delim then followed by optional suffix.

In omniparser it's a bit more flexible/powerful as you can specify string as seg delim so in this case `'\n` is a good way to write the schema.
