### ISSUE TITLE
Ignore blank rows CSV

### ISSUE THREAD

**Issue by DGollings** [jf-tech/omniparser#140]
Hi,

encountered a csv (converted from xlsx) where one line was all blank (,,,,,,)

Errored on 'cannot convert "" to int'

Now I fixed it at the source, but in general, it might be useful to add the option 'ignore blank row' or be able to set a default (like you can in EDI) for empty values? Especially when casting?
(in this case, setting '' to 0)

**Comment by jf-tech** [comment]
Try using `xpath` on `FINAL_OUTPUT` like in this CSV example: https://github.com/jf-tech/omniparser/blob/4aa56d6cb9b86be1bb9f26daf355a0cbe821b839/extensions/omniv21/samples/csv/1_weather_data_csv.schema.json#L24

**Comment by DGollings** [comment]
Checked the example:
```
DATE|HIGH TEMP C|LOW TEMP F|WIND DIR|WIND SPEED KMH|NOTE|LAT|LONG|UV INDEX
2019/01/31T12:34:56-0800|10.5|30.2|N|33|note 1|37.7749|122.4194|12/4/6
N/A
(..)
```

I mean even emptier :)

**Comment by DGollings** [comment]
thanks, that would work, just check a mandatory field
