### ISSUE TITLE
JSON schema validation only allows alphanumeric property names

### ISSUE THREAD

**Issue by Plenituz** [jf-tech/omniparser#144]
When using a valid template with non alphanumeric names for the properties, omniparser refuses the template because of patternProperties declaration such as this one: https://github.com/jf-tech/omniparser/blob/master/extensions/omniv21/validation/transformDeclarations.json#L87, in combination with the `additionalProperties: false`

Example of a template (notice the `$` in the property name):
```json
{
    "parser_settings": {
        "version": "omni.2.1",
        "file_format_type": "json"
    },
    "transform_declarations": {
        "FINAL_OUTPUT": {
            "object": {
                "$test": { "xpath": "/foo/bar" }
            }
        }
    }
}
```

Which returns this error:
```
transform_declarations.FINAL_OUTPUT.object: Additional property $test is not allowed
transform_declarations.FINAL_OUTPUT.object: Additional property $test is not allowed
transform_declarations.FINAL_OUTPUT: Must validate one and only one schema (oneOf)
transform_declarations.FINAL_OUTPUT: Must validate one and only one schema (oneOf)
```

Happy to provide additional information if needed.

Thanks

**Comment by jf-tech** [comment]
Thanks @Plenituz , with this hindsight, it does seem to better have less output property naming restrictions than more. After all, if a property name isn't right it's just a schema change, no need for the framework to hammer down a heavy hand.

I will look into a fix.

**Comment by jf-tech** [comment]
merged into master
