### ISSUE TITLE
JSON/XML to EDI conversion

### ISSUE THREAD

**Issue by sankethpb** [jf-tech/omniparser#146]
Could you please clarify if JSON / XML data can be converted to EDI EDIFACT data?
If feasible, could you please provide a small example?
Thank you in advance.

**Comment by jf-tech** [comment]
No. This parser is all about ingestion (various supported formats) and transforming (into JSON). The library has two types of EDI readers but doesn't have/include an EDI writer.

**Comment by sankethpb** [comment]
Thank you, would there be any plans to include a EDI writer in future?

**Comment by jf-tech** [comment]
At this moment, no. But I'd like to have a detailed sample so I can consider/plan for it.

**Comment by jf-tech** [comment]
@sankethpb closing this issue. Feel free to reopen it when you sample to provide.
