### ISSUE TITLE
EDIFACT parser segment skip

### ISSUE THREAD

**Issue by cnnelrib** [jf-tech/omniparser#147]
Could you please let me know if it's possible to skip a segment if it's not declared on schema but it's present on the input and vice versa?

Error generated: 
bad request: transform failed. err: input 'test-input' at segment no.8 (char[247,247]): segment 'details/NAD' needs min occur 1, but only got 0
Input:
UNA:+.? '
UNB+UNOC:3+9999999999999:14+9999999999998:14+210419:1622+446047262+ORDERS'
UNH+1+ORDERS:D:96A:UN:EAN008'
BGM+220::9+6666666666+9'
DTM+137:20210419:102'
DTM+2:20210518:102'
FTX+PUR+3++STORE ORDER:DR01'
RFF+PUR+3++STORE ORDER PLEN:DR01'
NAD+BY+9999999999999::9'

Schema:
{
    "parser_settings":{
        "version":"omni.2.1",
        "file_format_type":"edi"
    },
    "file_declaration":{
        "segment_delimiter":"'",
        "element_delimiter":"+",
        "component_delimiter":":",
        "ignore_crlf":true,
        "segment_declarations":[
            {
                "name":"details",
                "is_target":true,
                "type":"segment_group",
                "min":0,
                "max":-1,
                "child_segments":[
                    {
                        "name":"UNA",
                        "elements":[
                            {
                                "name":"random1",
                                "index":1
                            }
                        ]
                    },
                    {
                        "name":"UNB",
                        "elements":[
                            {
                                "name":"syntaxIdentifier",
                                "index":1
                            },
                            {
                                "name":"buyerGln",
                                "index":2
                            },
                            {
                                "name":"sellerGln",
                                "index":3
                            },
                            {
                                "name":"docDate",
                                "index":4
                            },
                            {
                                "name":"transferNumber",
                                "index":5
                            },
                            {
                                "name":"documentType",
                                "index":6
                            }
                        ]
                    },
                    {
                        "name":"UNH",
                        "elements":[
                            {
                                "name":"documentType2",
                                "index":1
                            },
                            {
                                "name":"fileFormatType",
                                "index":2
                            }
                        ]
                    },
                    {
                        "name":"BGM",
                        "elements":[
                            {
                                "name":"orderType",
                                "index":1
                            },
                            {
                                "name":"orderNumber",
                                "index":2
                            },
                            {
                                "name":"SignatureForOriginal",
                                "index":3
                            }
                        ]
                    },
                    {
                        "name":"DTM",
                        "elements":[
                            {
                                "name":"qualifierDocDate",
                                "index":1,
                                "component_index":1
                            },
                            {
                                "name":"docDate",
                                "index":1,
                                "component_index":2
                            },
                            {
                                "name":"formatDate",
                                "index":1,
                                "component_index":3
                            }
                        ]
                    },
                    {
                        "name":"DTM",
                        "elements":[
                            {
                                "name":"qualifierDeliveryDate",
                                "index":1,
                                "component_index":1
                            },
                            {
                                "name":"deliveryDate",
                                "index":1,
                                "component_index":2
                            },
                            {
                                "name":"deliveryformatDate",
                                "index":1,
                                "component_index":3
                            }
                        ]
                    },
                    {
                        "name":"FTX",
                        "elements":[
                            {
                                "name":"containPurchaseInformation",
                                "index":1
                            },
                            {
                                "name":"defaultValue",
                                "index":2
                            },
                            {
                                "name":"freeText1",
                                "index":4,
                                "component_index":1
                            },
                            {
                                "name":"freeText2",
                                "index":4,
                                "component_index":2
                            }
                        ]
                    },
                    {
                        "name":"NAD",
                        "elements":[
                            {
                                "name":"partyQualifier1",
                                "index":1
                            },
                            {
                                "name":"partyGln1",
                                "index":2,
                                "component_index":1
                            },
                            {
                                "name":"partyIDcode1",
                                "index":2,
                                "component_index":3
                            }
                        ]
                    }
                ]
            }
        ]
    },
    "transform_declarations":{
        "FINAL_OUTPUT":{
            "object":{
                "una_elem1":{
                    "xpath":"UNA/random1"
                },
                "header1":{
                    "object":{
                        "syntaxIdentifier":{
                            "xpath":"UNB/syntaxIdentifier"
                        },
                        "buyerGln":{
                            "xpath":"UNB/buyerGln"
                        },
                        "sellerGln":{
                            "xpath":"UNB/sellerGln"
                        },
                        "docDate":{
                            "xpath":"UNB/docDate"
                        },
                        "transferNumber":{
                            "xpath":"UNB/transferNumber"
                        },
                        "documentType":{
                            "xpath":"UNB/documentType"
                        }
                    }
                },
                "heade2":{
                    "object":{
                        "documentType2":{
                            "xpath":"UNH/documentType2"
                        },
                        "fileFormatType":{
                            "xpath":"UNH/fileFormatType"
                        }
                    }
                },
                "document":{
                    "object":{
                        "documentType2":{
                            "xpath":"BGM/orderType"
                        },
                        "orderNumber":{
                            "xpath":"BGM/orderNumber"
                        },
                        "SignatureForOriginal":{
                            "xpath":"BGM/SignatureForOriginal"
                        }
                    }
                },
                "docDate":{
                    "object":{
                        "qualifierDocDate":{
                            "xpath":"DTM/qualifierDocDate"
                        },
                        "docDate":{
                            "xpath":"DTM/docDate"
                        },
                        "formatDate":{
                            "xpath":"DTM/formatDate"
                        }
                    }
                },
                "deliveryDate":{
                    "object":{
                        "qualifierDeliveryDate":{
                            "xpath":"DTM/qualifierDeliveryDate"
                        },
                        "deliveryDate":{
                            "xpath":"DTM/deliveryDate"
                        },
                        "deliveryformatDate":{
                            "xpath":"DTM/deliveryformatDate"
                        }
                    }
                },
                "freeText":{
                    "object":{
                        "containPurchaseInformation":{
                            "xpath":"FTX/containPurchaseInformation"
                        },
                        "defaultValue":{
                            "xpath":"FTX/defaultValue"
                        },
                        "freeText1":{
                            "xpath":"FTX/freeText1"
                        },
                        "freeText2":{
                            "xpath":"FTX/freeText2"
                        }
                    }
                },
                "PartyInformation1":{
                    "object":{
                        "partyQualifier":{
                            "xpath":"NAD/partyQualifier1"
                        },
                        "partyGln":{
                            "xpath":"NAD/partyGln1"
                        },
                        "partyIDcode":{
                            "xpath":"NAD/partyIDcode1"
                        }
                    }
                }
            }
        }
    }
}

**Comment by jf-tech** [comment]
- If a seg is declared in schema but not in input: that makes the seg optional, use `"min": 0` for the seg declaration in schema.
- if a seg is in input, it must be declared in schema. We don't support skipping unrecognized seg. Can you show me a case/example that could warrant such feature addition?

**Comment by cnnelrib** [comment]
Hello,

If a seg is declared in schema but not in input: that makes the seg optional, use "min": 0 for the seg declaration in schema.
**I think this option will fix all the issue for me.**

if a seg is in input, it must be declared in schema. We don't support skipping unrecognized seg. Can you show me a case/example that could warrant such feature addition?
 **I was not aware of first option with "min": 0.**

Thank you!

**Comment by jf-tech** [comment]
@cnnelrib you might want to take a look at the readme about [EDI schema writing](https://github.com/jf-tech/omniparser/blob/master/doc/edi_in_depth.md)
