### ISSUE TITLE
Protobuf input support

### ISSUE THREAD

**Issue by JensRantil** [jf-tech/omniparser#148]
I was looking at converting protobuf to JSON. This tool would be useful if it supported that.

**Comment by jf-tech** [comment]
@JensRantil can you elaborate? What would the input look like? A single object encoded in protobuf or a stream of objects? Some sample scenarios would be great for us to evaluate.

**Comment by jf-tech** [comment]
@JensRantil closing the ticket due no activities. Please reopen when you have more details. Thanks.
