### ISSUE TITLE
Question-make an error when processing csv  separated by commas

### ISSUE THREAD

**Issue by wujunyi792** [jf-tech/omniparser#153]
when processing a cell containing "," in it, it will be divided into multiple pieces,although the whole cell is wrapped in quotation marks
The csv data :
![image](https://user-images.githubusercontent.com/53227298/139001822-26576d15-0468-41e9-8a28-b9495433f622.png)
The parsing result:
![image](https://user-images.githubusercontent.com/53227298/139001887-0a757b9c-5320-41d5-ab11-fb65fb8fe298.png)

Is it my default?

**Comment by jf-tech** [comment]
Closed due to lack of activities.
