### ISSUE TITLE
Type casting for output

### ISSUE THREAD

**Issue by andrey-moor** [jf-tech/omniparser#162]
Hey @jf-tech,

I have a question about the type casting: we actually need to be able to specify the type to safe cast the value to, instead of relying on the source format type. 

The example of the scenario: take a JSON payload and transform it into a Parquet or SQL set of records. Both have extended value types such as DATE, TIME and others. Currently, the only way to achieve that is to have another schema with column/type mappings and type handlers, which seems a little bit redundant. 

It'd be great if we can somehow specify it in the schema and have it as a source of truth.

```
{
    "parser_settings": {
        "version": "omni.2.1",
        "file_format_type": "json"
    },
    "transform_declarations": {
        "FINAL_OUTPUT": { "xpath": "/publishers/*/books/*[author!='']", "object": {
            "publisher_name": { "xpath": "../../name", "type": "string" },
            "author": { "xpath": "author", type: "string" },
            "year": { "xpath": "year", "type": "date" },
            "price": { "xpath": "price", "type": "double" },
            "title": { "xpath": "title",  type: "string" }
        }}
    }
}
```

Is it something that could be extended programmatically? Does it make any sense to you?

**Comment by jf-tech** [comment]
omniparser has a limited supported builtin types: https://github.com/jf-tech/omniparser/blob/master/doc/transforms.md#miscellaneous, namely `int`, `float` (which actually means `float64`, so your `double` is covered), `boolean`, and `string`. By default it's `string` if you don't specify `type` keyword in your transform.

But for `date` there is no such a builtin type. I don't know what the date type specifically is. However there might be a way to use `javascript` custom_func to achieve it. Let me know what the type `date` actually means in JSON/golang...

**Comment by andrey-moor** [comment]
I totally forgot about custom functions, thank you, I think that might do the trick
