### ISSUE TITLE
Error in go get install latest version

### ISSUE THREAD

**Issue by deokapil** [jf-tech/omniparser#176]
Hi,

I am getting following error while installing the latest version v1.0.2 of omniparser

`extensions/omniv21/fileformat/flatfile/fixedlength/.snapshots/TestReadAndMatchRowsBasedEnvelope-non-empty_buf;_no_read;_match;_create_IDR: malformed file path "extensions/omniv21/fileformat/flatfile/fixedlength/.snapshots/TestReadAndMatchRowsBasedEnvelope-non-empty_buf;_no_read;_match;_create_IDR": invalid char ';'`

probably accidental typo in file name is checked in

**Comment by jf-tech** [comment]
Are you running on Windows?

**Comment by jf-tech** [comment]
Okay, not related to your OS. It's from here:

https://cs.opensource.google/go/x/mod/+/master:module/module.go;l=285;drc=02c991387e35f9e4c0a9b7ce137717055f8d716d

Basically module file names have a reduced set of valid characters. And the two recently introduced snapshot filenames contain `;` and while it's all good in coding, testing, and CI, it's failing during import.

I'll scrub all the use of `;` from all test names.

**Comment by jf-tech** [comment]
Also filed a ticket with https://github.com/bradleyjkemp/cupaloy/issues/83

**Comment by jf-tech** [comment]
The issue should be fixed now with release of 1.0.3. Give it another try.
