### ISSUE TITLE
CSV Example

### ISSUE THREAD

**Issue by bjordan2010** [jf-tech/omniparser#182]
I am following the CSV Example.  The schema includes a header of "header": "^DATE|HIGH TEMP C|LOW TEMP F|WIND DIR|WIND SPEED KMH|NOTE|LAT|LONG|UV INDEX$".

In package csv, decl.go's RowsBased (called from reader.go ReadAndMatch) function says if r.Header == nil then it's rows based but the line above makes the header not nil? So now it thinks my CSV is Header and Footer based.

What am I missing?

**Comment by jf-tech** [comment]
@bjordan2010

Good question. I assume you're following the example in [Getting Started](https://github.com/jf-tech/omniparser/blob/master/doc/gettingstarted.md). If you look closely at the [final schema](https://github.com/jf-tech/omniparser/blob/master/doc/gettingstarted.md#the-schema) in that doc page, you'll see there are two records under the `file_declaration.records` section: one for the header line and the other for the data lines.

In `csv` (actually `csv2` to be more precise) schema, you can declare multiple (and nested if needed) records, each of which can be either `rows` based or `header/footer` based, independently. The schema and parser work together like a state machine, allowing it to read, match, process, transform, and transition between records.

In the example, we have two records, the first one:
```
            {
                "header": "^DATE|HIGH TEMP C|LOW TEMP F|WIND DIR|WIND SPEED KMH$",
                "min": 1, "max": 1
            }
```
It says, the record is `header`/`footer` based (in this case, no `footer` is specified, thus as long as `header` regex matches, the current line of data is identified with/matched to this record. Also this record has `min`/`max` both `= 1`, which means after a line matches to the record, the next line will automatically move on and attempt to match subsequent records: the state machine transition code for this is in [HierarchyReader.recDone() function](https://github.com/jf-tech/omniparser/blob/master/extensions/omniv21/fileformat/flatfile/hierarchyReader.go#L240), where `recDone()` is called when the current data has been fully matched to the record and finished processing thus needing to move to the next record (by calling `recNext()` when the number of matched and processed instances of the current record has exceeded the declared `max`).

Once the state machine moved to the next record, which in the case of this example is:
```
            {
                "is_target": true,
                "columns": [
                    { "name": "DATE" },
                    { "name": "HIGH_TEMP_C" },
                    { "name": "LOW_TEMP_F" },
                    { "name": "WIND_DIR" },
                    { "name": "WIND_SPEED_KMH" }
                ]
            }
```
Lots of default omissions here (all defaults are explained in the [`file_declaration`](https://github.com/jf-tech/omniparser/blob/master/doc/csv2_in_depth.md#csv-file_declaration) section):
- `rows` omitted, thus defaulted to 1.
- `min`/`max` omitted, thus defaulted to 0/-1 respectively.
Now the state machine will pretty much loop on this record forever, processing each data line as a record.

Hopefully this explains how the `csv` processing state machine transitions.

For detailed usage reference: [CSV Schema in Depth](https://github.com/jf-tech/omniparser/blob/master/doc/csv2_in_depth.md) (also linked from the root [README.md](https://github.com/jf-tech/omniparser/blob/master/README.md#documentation)).

For code inspection/review, I suggest you take a close look at the package [`flatfile`](https://github.com/jf-tech/omniparser/tree/master/extensions/omniv21/fileformat/flatfile), where we have two main interfaces: `RecDecl` and `RecReader` and the core state machine reader `HierarchyReader`. Once you understand how this package works, the rest (currently we only have `csv` and `fixedlength`) simply fall into place.

**Comment by bjordan2010** [comment]
Thanks for responding.  I have narrowed my problem down to the min: 1 max:
1 setting.  Apparently I have something wrong in my header which I am
building dynamically based on the file.  I'm going to research the problem
this morning and I'll let you know if it's a bug on my end.  I also has to
specify is_target: false on the header row otherwise it would process it
but that may be related to me removing the min/max while troubleshooting.

I expect CSV to be processed as row based not header / footer based, is
that a correct assumption or will it be processed as a header / footer with
no footer?  If we get this working I'm going to ask my client to donate, if
they will not, then I will myself.  I appreciate the work you have put into
this project.

Thanks,

Jesse

**Comment by bjordan2010** [comment]
I am getting the following error when processing file_format_type csv2:

input 'my_file' line 1: record/record_group '' needs min occur 1, but only
got 0

My header in schema:
""^FillDate,PharmacyID,PharmacyName,PHARMACY ZIP
CODE,PRESCRIPTIONSERVICEREFERENCENU,NDC11,NameNameExt,GenericDrugName,Brnd
Gen Compound,BG,Compound,OTC Indicator,MAC Price,Formulary,Mail
Retail,Channel,NUMBEROFREFILLSAUTHORIZED,Qty,Days,RxCount,ClaimStatus,INGREDIENTCOSTSUBMITTED,AWP100,UNC,IngredCost,DispFee,SalesTax,Gross,PlanPaidAmount,PatientPaidAmount,RebillAmtApplPerDedu,Mbr
Pay minus Ded,DAWCode$,"

My header row in the CSV file:
FillDate,PharmacyID,PharmacyName,PHARMACY ZIP
CODE,PRESCRIPTIONSERVICEREFERENCENU,NDC11,NameNameExt,GenericDrugName,Brnd
Gen Compound,BG,Compound,OTC Indicator,MAC Price,Formulary,Mail
Retail,Channel,NUMBEROFREFILLSAUTHORIZED,Qty,Days,RxCount,ClaimStatus,INGREDIENTCOSTSUBMITTED,AWP100,UNC,IngredCost,DispFee,SalesTax,Gross,PlanPaidAmount,PatientPaidAmount,RebillAmtApplPerDedu,Mbr
Pay minus Ded,DAWCode

My full file_declaration section:
"file_declaration": {
        "delimiter": ",",
        "records": [
            {
                "header": "^FillDate,PharmacyID,PharmacyName,PHARMACY ZIP
CODE,PRESCRIPTIONSERVICEREFERENCENU,NDC11,NameNameExt,GenericDrugName,Brnd
Gen Compound,BG,Compound,OTC Indicator,MAC
Price,Formulary,Mail/Retail,Channel,NUMBEROFREFILLSAUTHORIZED,Qty,Days,RxCount,ClaimStatus,INGREDIENTCOSTSUBMITTED,AWP100,UNC,IngredCost,DispFee,SalesTax,Gross,PlanPaidAmount,PatientPaidAmount,RebillAmtApplPerDedu,Mbr
Pay minus Ded,DAWCode$",
                "min": 1, "max": 1, "is_target": false
            },
            {
                "is_target": true,
                "columns": [
                    { "name": "FillDate" },
                    { "name": "PharmacyID" },
                    { "name": "PharmacyName" },
                    { "name": "PHARMACY_ZIP_CODE" },
                    { "name": "PRESCRIPTIONSERVICEREFERENCENU" },
                    { "name": "NDC11" },
                    { "name": "NameNameExt" },
                    { "name": "GenericDrugName" },
                    { "name": "Brnd_Gen_Compound" },
                    { "name": "BG" },
                    { "name": "Compound" },
                    { "name": "OTC_Indicator" },
                    { "name": "MAC_Price" },
                    { "name": "Formulary" },
                    { "name": "Mail Retail" },
                    { "name": "Channel" },
                    { "name": "NUMBEROFREFILLSAUTHORIZED" },
                    { "name": "Qty" },
                    { "name": "Days" },
                    { "name": "RxCount" },
                    { "name": "ClaimStatus" },
                    { "name": "INGREDIENTCOSTSUBMITTED" },
                    { "name": "AWP100" },
                    { "name": "UNC" },
                    { "name": "IngredCost" },
                    { "name": "DispFee" },
                    { "name": "SalesTax" },
                    { "name": "Gross" },
                    { "name": "PlanPaidAmount" },
                    { "name": "PatientPaidAmount" },
                    { "name": "RebillAmtApplPerDedu" },
                    { "name": "Mbr_Pay_minus_Ded" },
                    { "name": "DAWCode" }
                ]
            }
        ]
    },

If I put both of the values for the header in a file, and I search on the
first one without the double quotes, ^, and $, they match, so I'm not sure
why I'm getting the error.  I will continue to debug but following the
Getting Started example this should work even without "is_target": false.
The only differences I see is the example uses a pipe | delimiter and far
fewer fields.

Thanks,

Jesse

**Comment by bjordan2010** [comment]
I may be wrong but here is what I found in debugging. In decl.go's
matchLine function, line.raw gets passed in to re.MatchString which calls
doMatch will a nil io.RuneReader which calls doExecute with the same nil r,
which second line is return nil if r == nil.  Meaning no match.  Is this a
bug in MatchString?

**Comment by bjordan2010** [comment]
Meh it was a simple bug.  I had inadvertently placed the , for the header
line inside the quote when dynamically building the header line.  Sorry to
waste your time but I appreciate your prior response.

Thanks,

Jesse

**Comment by jf-tech** [comment]
@bjordan2010 

A couple thoughts/tips:

1) check out the "CSV Schema in Depth" doc which contains many scenarios - sometimes the easiest the way is to simply skip header row verification (https://github.com/jf-tech/omniparser/blob/master/doc/csv2_in_depth.md#use-case-simple-csv-with-header-but-header-verification-not-needed)

2) note the header match is regex based so you might find using tool like https://regex101.com/ to test your header pattern in your schema against the actual header in your data file to see if they match or not.

Appreciate you kindness! Let me know if any other problems you need help with.

**Comment by jf-tech** [comment]
@bjordan2010, Do you still have any issues? Can we close the ticket now?

**Comment by bjordan2010** [comment]
@jf-tech All is well, thanks for your help.
