### ISSUE TITLE
Is it possible to chain javascript custom functions?

### ISSUE THREAD

**Issue by bjordan2010** [jf-tech/omniparser#185]
Hello.  I was wondering if Is it possible to chain javascript or javascript_with_context custom functions? I haven't been able to get the right syntax if so.  If I swap the value for name below from concat to javascript and add javascript args I get either invalid number of args or ILLEGAL javascript or cannot specify 'xpath' or 'xpath_dynamic' on both [sic: field and template].

I was able to figure out how to chain javascript and built in functions below.  If not is the only solution to attempt to code both operations in a single javascript function?

```
"left_pad_with_zero_for_7_and_append_dash_old": {
	"custom_func": {
		"name": "concat",
		"args": [
			{
				"custom_func": {
					"name": "javascript",
					"args": [
						{
							"const": "if (x.length < 7) { i=0; b=7-x.length; for (i=0; i < b; i++) { x = '0' + x}} else { x };"
						},
						{ 
							"const": "x"
						},
						{
							"xpath": "."
						}
					]
				}
			},
			{
				"const": "-old"
			}
		]
	}
}
```

**Comment by jf-tech** [comment]
I tried locally with `./cli.sh` (but you can also use the [playground](https://omniparser-prod-omniparser-qd0sj4.mo2.mogenius.io/) as well for quick trial), using the [`1_single_row.input.csv`](https://github.com/jf-tech/omniparser/blob/master/extensions/omniv21/samples/csv2/1_single_row.input.csv) and [`1_single_row.schema.json`](https://github.com/jf-tech/omniparser/blob/master/extensions/omniv21/samples/csv2/1_single_row.schema.json), by just adding one extra field into the `FINAL_OUTPUT` as follows:

```
            "left_pad_with_zero_for_7_and_append_dash_old": {
                "custom_func": {
                    "name": "javascript",
                    "args": [
                        { "const": " 'test-' + mytext + '-old'; "},
                        { "const": "mytext" },
                        {
                            "custom_func": {
                                "name": "javascript",
                                "args": [
                                    {
                                        "const": "if (x.length < 7) { i=0; b=7-x.length; for (i=0; i < b; i++) { x = '0' + x}} else { x };"
                                    },
                                    {
                                        "const": "x"
                                    },
                                    {
                                        "xpath": "LOW_TEMP_F"
                                    }
                                ]
                            }
                        }
                    ]
                }
            },
```

(Note the chaining of the `custom_func` `javascript` above)

It correctly outputs the desired field:

```
        "left_pad_with_zero_for_7_and_append_dash_old": "test-00030.2-old",
```

However with what being said above, my question is why do you even want to chain `javascript` `custom_func`s? Why not just have one `javascript` `custom_func` and does the "chaining" inside the script?

**Comment by bjordan2010** [comment]
Thank you for the help.  Using the command line locally is how I was
testing.

In answer to your question, I am then building the schema dynamically based
on the header in a file and having the user map the read field to the write
field.  I am also building the transforms based on user input dynamically
as well.

For reusability, it is often easier to chain complex transforms, than to
combine them into a single transform.  Concatenating a literal to the data
was just a simple example to prove multiple transforms on a single field
was doable.  Some of the other manipulations are quite complex and have an
order of operation which could be difficult to combine but are easy to
chain.

**Comment by jf-tech** [comment]
@bjordan2010 Understand. Thanks for the explanation. Let me know if there is anything else needing help or I'll close the ticket soon.

**Comment by bjordan2010** [comment]
Good to close. Thanks again for the help.

**Comment by jf-tech** [comment]
@bjordan2010 closing, and if you have any other helps or feature requests, don't hesitate to contact us.
