### ISSUE TITLE
Tab delimiter

### ISSUE THREAD

**Issue by bjordan2010** [jf-tech/omniparser#188]
Is it possible to use tab as a file delimiter?  If so, what is the proper way to assign it?  Should the header use tabs as well?

**Comment by jf-tech** [comment]
@bjordan2010 Yes. I've pushed a [branch](https://github.com/jf-tech/omniparser/tree/issue_188_tab) to demonstrate how it is done:

- Take a look the [1_single_row.input.csv](https://github.com/jf-tech/omniparser/blob/issue_188_tab/extensions/omniv21/samples/csv2/1_single_row.input.csv), note the use of TAB as delimiter in the csv file.
- Take a look the [1_single_row.schema.json](https://github.com/jf-tech/omniparser/blob/issue_188_tab/extensions/omniv21/samples/csv2/1_single_row.schema.json), note the use of ```"delimiter": "\t"``` and the way we can do header matching/verification by ```"header": "^DATE\tHIGH TEMP C\tLOW TEMP F\tWIND DIR\tWIND SPEED KMH\tNOTE\tLAT\tLONG\tUV INDEX$"```.

**Comment by bjordan2010** [comment]
Great that works.  Thank you.
