### ISSUE TITLE
Mogenius not responding ever after waiting several minutes

### ISSUE THREAD

**Issue by gaurav-amagi** [jf-tech/omniparser#189]
Hi team,

I tried the playground for Omniparser to try out schemas but the screen is stuck and not responding for several minutes. 
 Can you have a look at it?

**Comment by jf-tech** [comment]
Unfortunately both haroku and mogenius get rid of free tier and I'm in search for another hosting solution.

In the mean while you can clone the repo and use `./cli.sh` to test out schemas and inputs.
