### ISSUE TITLE
XLSX Parsing

### ISSUE THREAD

**Issue by MrRobo-t** [jf-tech/omniparser#191]
Hi team,

I have a use case of parsing xlsx files. Not sure how to do it right now using custom file formats.  I am looking to parse single sheet as well as multisheet xlsx files. Can you guys drop in an example around it?

**Comment by jf-tech** [comment]
We never dealt with xlsx files before. The best way to go is to provide a pair (or multiple pairs) of input xlsx and desired output json - so we can take a look at the feasibility.

**Comment by MrRobo-t** [comment]
OK.. Thanks for this.. Really appreciate your response.

I am working on a csv file and want to skip the first line which contains junk value, the second line contains my headers.. How can I make the schema understand that my headers begin from second row?

A,B,,
1,2,3,4

**Comment by jf-tech** [comment]
@MrRobo-t We'd appreciate the compartmentalization of each ticket/issue - i.e. one issue one ticket. If you're okay, I'd like to close this ticket about parsing xlsx file, and open a new ticket on the csv parsing question you have. And by the way, it is quite trivial to do what you've asked for the csv header parsing.

Agree?

**Comment by MrRobo-t** [comment]
Agreed.. Please raise the new ticket.. Apologies for this.. Yes it is trivial but I am unable to find this :(
