### ISSUE TITLE
Skip a line before parsing a csv header line

### ISSUE THREAD

**Issue by jf-tech** [jf-tech/omniparser#194]
From @MrRobo-t
>> OK.. Thanks for this.. Really appreciate your response.
>> 
>> I am working on a csv file and want to skip the first line which contains junk value, the second line contains my headers.. How >> can I make the schema understand that my headers begin from second row?
>> 
>> A,B,,
>> 1,2,3,4

**Comment by jf-tech** [comment]
Essentially you combine the two techniques described in the [CSV in Depth](https://github.com/jf-tech/omniparser/blob/master/doc/csv2_in_depth.md) together to achieve this:
1) [How to skip a line without consuming it](https://github.com/jf-tech/omniparser/blob/master/doc/csv2_in_depth.md#use-case-simple-csv-with-header-but-header-verification-not-needed)
2) [How to parse and validate a header](https://github.com/jf-tech/omniparser/blob/master/doc/csv2_in_depth.md#use-case-simple-csv-with-header-and-header-verification-needed)

So your schema would look like this:

```
  "file_declaration": {
      "delimiter": ",",
      "records": [
          { "rows": 1, "min": 1, "max": 1 },
          {
              "min": 1, "max": 1,
              "header": "^C1,C2,C3,C4$"
          },
          {
              "is_target": true,
              "columns": [
                  { "name": "COL1" },
                  { "name": "COL2" },
                  { "name": "COL3" },
                  { "name": "COL4" }
          ]}
      ]
  },
```

Explanation:
- The first record in the schema says this record consists of a single row and maximum number of instances for this record is 1, thus effectively only consuming a single line (and the very first line) of the source csv file. Since this record isn't marked with `is_target:true` thus it's discarded.
- The second record in the schema says this record is identified by a `header` regex, and the header line from the csv file must match the regex pattern or the injestion operation would fail. But again since the record isn't marked with `is_target:true`, the content is discarded - since we really only interested in validating the header row.
- The first record is the real meat, and pretty sure you're familiar with how it works.

With all the combinations described in the  [CSV in Depth](https://github.com/jf-tech/omniparser/blob/master/doc/csv2_in_depth.md), you have immense flexibility to parse files with omniparser.

Let me know if there are any other questions.

**Comment by MrRobo-t** [comment]
Ah! Great explanation.. Sorts out the problem and works like a charm.. 
Thank you for this @jf-tech :)
