### ISSUE TITLE
Omniparser gives duplicate records incase of missing values

### ISSUE THREAD

**Issue by MrRobo-t** [jf-tech/omniparser#195]
Hi I am working on a csv file with some missing values:

INPUT
A,B,C,D,E
1,2,3,4,5
4,5,6,7,8
,,,13,14
,,,16,17

SCHEMA:
`{
  "parser_settings": {
    "version": "omni.2.1",
    "file_format_type": "csv2"
  },
  "file_declaration": {
    "delimiter": ",",
    "replace_double_quotes": false,
    "records": [{
      "min": 1,
      "max": 1,
      "header": "^A,B,C,D,E$"
    },
      {
        "is_target": true,
        "columns": [{
          "name": "A"
        },
          {
            "name": "B"
          },
          {
            "name": "C"
          },
          {
            "name": "D"
          },
          {
            "name": "E"
          }
        ]
      }
    ]
  },
  "transform_declarations": {
    "FINAL_OUTPUT": {
      "object": {
        "a": {
          "xpath": "A",
          "type": "int"
        },
        "b": {
          "xpath": "B",
          "type": "string"
        },
        "c": {
          "xpath": "C",
          "type": "string"
        },
        "d": {
          "xpath": "D",
          "type": "string"
        },
        "e": {
          "xpath": "E",
          "type": "string"
        }
      }
    }
  }
}`

The first 2 records are processed neatly but the last 2 records gives the duplicate result of the "4,5,6,7,8,9
"

OUTPUT:
```
{
 "Result": [
  {
   "a": 1,
   "b": "2",
   "c": "3",
   "d": "4",
   "e": "5"
  },
  {
   "a": 4,
   "b": "5",
   "c": "6",
   "d": "7",
   "e": "8"
  },
  {
   "a": 4,
   "b": "5",
   "c": "6",
   "d": "7",
   "e": "8"
  },
  {
   "a": 4,
   "b": "5",
   "c": "6",
   "d": "7",
   "e": "8"
  }
 ]
}


```

How can I ignore such records?

**Comment by MrRobo-t** [comment]
The issue pops up when a target column input values comes as empty, the omniparser is replicating values from the previous record. So, if the first target column is empty, the entire row gets replicated of the previous parsed record. If the second value of the column comes as empty, it parses the current value of the first column and replicates values from the second column of the previous record. Looks like a bug. Ideally it should parse the value as empty ""/false/0 only

**Comment by jf-tech** [comment]
@MrRobo-t I don't know how you came to encounter the problem you described: via `cli.sh` or programmatically? Because in with `./cli.sh` I cut/paste exactly your input and schema and it gave me an error after the first two data lines of processing:

```
$ cat 1.csv 
───────┬──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
       │ File: 1.csv
───────┼──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
   1   │ A,B,C,D,E
   2   │ 1,2,3,4,5
   3   │ 4,5,6,7,8
   4   │ ,,,13,14
   5   │ ,,,16,17
───────┴──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
$ cat 1.json -P
───────┬──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
       │ File: 1.json
───────┼──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
   1   │ {
   2   │   "parser_settings": {
   3   │     "version": "omni.2.1",
   4   │     "file_format_type": "csv2"
   5   │   },
   6   │   "file_declaration": {
   7   │     "delimiter": ",",
   8   │     "replace_double_quotes": false,
   9   │     "records": [
  10   │       {
  11   │         "min": 1,
  12   │         "max": 1,
  13   │         "header": "^A,B,C,D,E$"
  14   │       },
  15   │       {
  16   │         "is_target": true,
  17   │         "columns": [
  18   │           {
  19   │             "name": "A"
  20   │           },
  21   │           {
  22   │             "name": "B"
  23   │           },
  24   │           {
  25   │             "name": "C"
  26   │           },
  27   │           {
  28   │             "name": "D"
  29   │           },
  30   │           {
  31   │             "name": "E"
  32   │           }
  33   │         ]
  34   │       }
  35   │     ]
  36   │   },
  37   │   "transform_declarations": {
  38   │     "FINAL_OUTPUT": {
  39   │       "object": {
  40   │         "a": {
  41   │           "xpath": "A",
  42   │           "type": "int"
  43   │         },
  44   │         "b": {
  45   │           "xpath": "B",
  46   │           "type": "string"
  47   │         },
  48   │         "c": {
  49   │           "xpath": "C",
  50   │           "type": "string"
  51   │         },
  52   │         "d": {
  53   │           "xpath": "D",
  54   │           "type": "string"
  55   │         },
  56   │         "e": {
  57   │           "xpath": "E",
  58   │           "type": "string"
  59   │         }
  60   │       }
  61   │     }
  62   │   }
  63   │ }
───────┴──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
$ ./op transform -i 1.csv -s 1.json 
[
	{
		"a": 1,
		"b": "2",
		"c": "3",
		"d": "4",
		"e": "5"
	},
	{
		"a": 4,
		"b": "5",
		"c": "6",
		"d": "7",
		"e": "8"
	}
Error: input '1.csv' line 5: fail to transform. err: unable to convert value '' to type 'int' on 'FINAL_OUTPUT.a', err: strconv.ParseInt: parsing "": invalid syntax
Usage:
  op transform [flags]

Flags:
  -h, --help            help for transform
  -i, --input string    input file (optional; if not specified, stdin/pipe is used)
  -s, --schema string   schema file (required)

$ 
```

It's completely understandable: since your `column a` requires the output type be `int`, thus an empty string input value cannot be converted, failing the 3rd data line and processing thus halted.

Let me know how you got your duplicated lines of output then I can help you.

**Comment by jf-tech** [comment]
@MrRobo-t closing the ticket due to lack of activity. Reopen if you have more updates/info.

**Comment by MrRobo-t** [comment]
There were code issues.. My bad 🤦
