### ISSUE TITLE
How to add constant values in the schema?

### ISSUE THREAD

**Issue by MrRobo-t** [jf-tech/omniparser#196]
I was wondering if we can add constants to our schema. I was able to add strings but unable to add boolean values.. Is there a way? I checked the docs but didn't find much.

**Comment by jf-tech** [comment]
`"col5": { "const": "true", "type": "boolean" }`

More technical details/reference check https://github.com/jf-tech/omniparser/blob/master/doc/transforms.md

**Comment by MrRobo-t** [comment]
Cool.. Works fine :) Thanks for this
