### ISSUE TITLE
Non-authenticating EDI segment reader, any examples?

### ISSUE THREAD

**Issue by tb-artomu** [jf-tech/omniparser#199]
Non-authenticating EDI segment reader, any examples?

**Comment by jf-tech** [comment]
https://github.com/jf-tech/omniparser/blob/master/doc/programmability.md#non-validating-edi-segment-reader？

**Comment by tb-artomu** [comment]
thanks.

JF Technology ***@***.***> 于2023年4月12日周三 02:23写道：
