### ISSUE TITLE
[EDI] Support repetition separator

### ISSUE THREAD

**Issue by manuel-neuhauser-hs** [jf-tech/omniparser#212]
For EDI input files, the [repetition separator](https://www.stedi.com/edi/x12/element/I65) is currently not supported in omniparser. It is used to allow for multipe values in a composite element.

## Example

The following `ISA` segment defines `^` as the repetition separator, and segment `DMG` uses it in the 5th element to list 2 composite values.

```
ISA*00*          *00*          *ZZ*CMSFFM         *ZZ*987654321      *230614*1605*^*00501*000001001*1*T*:~
...
DMG*D8*19910512*M*M*:RET:2135-2^:RET:2106-3~
```

```bash
$ op transform --schema 834-schema-repetition.json.txt --input 987654321.I834.D230614.T161330125.T.OUT.txt
```

#### Actual
```json
[
  {
    "race_ethnicity_code": [
      "2135-2^"
    ]
  }
]
```

#### Expected
```json
[
  {
    "race_ethnicity_code": [
      "2135-2",
      "2106-3"
    ]
  }
]
```

### Files

[834-schema-repetition.json.txt](https://github.com/jf-tech/omniparser/files/12113591/834-schema-repetition.json.txt)

[987654321.I834.D230614.T161330125.T.OUT.txt](https://github.com/jf-tech/omniparser/files/12113590/987654321.I834.D230614.T161330125.T.OUT.txt)

**Comment by jf-tech** [comment]
@manuel-neuhauser-hs ack. Will get back to you with a solution early next week.

**Comment by jf-tech** [comment]
@manuel-neuhauser-hs a prototype is WIP. Will keep you updated.

**Comment by jf-tech** [comment]
[212.diff.txt](https://github.com/jf-tech/omniparser/files/12156810/212.diff.txt)

Attached a working prototype diff. Now need to formalize the changes

**Comment by manuel-neuhauser-hs** [comment]
@jf-tech – Tested our use case and additionally tried several edge cases, and the outputs and errors are as expected. Thanks for the lightning fast addition of this feature. 🚀

**Comment by jf-tech** [comment]
> @jf-tech – Tested our use case and additionally tried several edge cases, and the outputs and errors are as expected. Thanks for the lightning fast addition of this feature. 🚀

@manuel-neuhauser-hs And thank you and your company's sponsorship! Highly appreciate it!

**Comment by jf-tech** [comment]
@manuel-neuhauser-hs are you in a hurry needing a new release to be cut or you can live with master for a while? The reason we're a bit hesitant against cutting a new release is that seems you and some other people are actively working on fairly complex EDI parsing and there could be more issues/requests coming up. Let us know.
