### ISSUE TITLE
EDI: xpath for segments within repeating segments with different identifiers

### ISSUE THREAD

**Issue by djn8984** [jf-tech/omniparser#216]
We are building schemas for EDI files.  With files that have repeating segment names, we are being more descriptive in the xpath to define which segment name we want specifically.  

For example, if the file has DTP*348 and DTP*349 segments within the the INS segment that defines the member record, we are using something like "loop_2300/DTP[dateTimeQualifier=348][1]/dateTimeQualifier" vs "loop_2300/DTP[dateTimeQualifier=349][1]/dateTimeQualifier"  to distinguish between the 348 and 349.  This is all working fine.

When using the same approach for REF segments, this is also working fine.  However, we have scenarios where the NM1 segment can repeat within a member record along with N3 and N4 segments within that and it is NOT working in those scenarios.

When trying to use an xPath of "loop_2100/N3/addressLine1", we get an error that it yielded more than one result, likely because there is more than one N3/addressLine1.

When trying to use an xPath of "loop_2100/NM1[entityIdentifierCode='IL'][1]/N3/addressLine1", it looks like it totally gets skipped in the mapping process.

Example snippet from file with mocked up data is below and attached.  You can see there is an NM1*1L with N3 and N4 segments following as well as an NM1*31 with N3 and N4 segments following.  We need to be able to pick which N3 (and N4) segment from a record that looks like this.

![image](https://github.com/jf-tech/omniparser/assets/123570392/b90540a7-484a-40a6-adde-9030c46c3d38)

[sampleRecordRepeatingNM1.txt](https://github.com/jf-tech/omniparser/files/12162941/sampleRecordRepeatingNM1.txt)

**Comment by manuel-neuhauser-hs** [comment]
Without knowing the `file_declaration` of your schema, this is just a guess. Using the `following-sibling::` operator may address your concern. The following example hasn't been tested.

```xpath
loop_2100/NM1[entityIdentifierCode='IL']/following-sibling::N3/addressLine1[1]
```

**Comment by djn8984** [comment]
Thank you!  I toyed around with it a little bit and believe I have it all working as expected now.  Just as an FYI, here is what worked:

I used "loop_2100/NM1[entityIdentifierCode='**IL**']/following-sibling::N3/addressLine1" and it is pulling the correct data point from the EDI file, which is the element with index 1 (which correlates to the addressLine1 element) of the N3 segment that is within the **NM1*IL** segment.

Also confirmed that using "loop_2100/NM1[entityIdentifierCode='**31**']/following-sibling::N3/addressLine1" correctly pulls the element with index 1 of the N3 segment that is within the **NM1*31** segment.

**Comment by jf-tech** [comment]
Thank you @manuel-neuhauser-hs for providing insight here!

@djn8984 don't know which EDI spec this data is from, but does `N3` always come with `NM1`? Is it possible in `segment_declarations` to declare `N3` under `NM1` as a child segment, this way, one of your original proposal `loop_2100/NM1[entityIdentifierCode='IL'][1]/N3/addressLine1` would work, I guess.

If no other questions, can you resolve the issue? Thank you!

(One last shameless bit, please consider sponsoring the project, any help we will be very grateful!)
