### ISSUE TITLE
How to target the last line?

### ISSUE THREAD

**Issue by husthoper** [jf-tech/omniparser#219]
![image](https://github.com/jf-tech/omniparser/assets/20582286/9afcc70a-6d86-45c8-bd3d-459da43a9023)
my input file has three part:head part

**Comment by husthoper** [comment]
my input file has three part: head part:

**Comment by husthoper** [comment]
my input file has three part:
1. head part has 3 line
2. body part may has 0 ~n line
3. tail part has 1 line
i need to tail part as the target, how can i to read the last line by configuration

**Comment by jf-tech** [comment]
@husthoper It would be nice if you could post a sample input file (with sensitive information removed or redacted of course) to illustrate the use case. That way we can see how to help.

**Comment by husthoper** [comment]
this file has 19 lines，i only need 19th line record

**Comment by jf-tech** [comment]
@husthoper if there is no special markings / tokens on the last line omniparser can look for, it's nearly impossible if you think about it:

- your first envelope (using ominiparser term) is fixed 3 lines. That's easy
- your 2nd envelope is of variable length, and has no special markings such as prefix, postfix or some special regex pattern, so omniparser wouldn't really know when the envelope finishes, would it? 
- you might say 2nd envelope finishes on the 2nd to last line, but that requires omniparser to know the entirety of the input. But it doesn't because it is a stream parser, (in your case) it reads one line at a time, it doesn't know whsts ahead of it.

Now of course it your input file isn't huge, you might figure out a "hacky" way to instruct the parser to read the whole file in as one record, then do just javascript custom function to parse the last line out. But now it's completely absurd and awkward way of using omniparser.

**Comment by husthoper** [comment]
thanks

**Comment by jf-tech** [comment]
@husthoper 

Yesterday I was thinking about another solution for you: if you know the last line always have the word "总   计", then I was thinking you might be able to use the envelope that uses `header` regex to match the pattern:

```
{ "name": "FOOTER",  "min": 1, "max": 1, "header": "^\s*总   计", "is_target": true }
```

So maybe you schema can look like this:

```
{
    "parser_settings": {
        "version": "omni.2.1",
        "file_format_type": "fixedlength2"
    },
    "file_declaration": {
        "envelopes" : [
            { "name": "HEADER", "min": 1, "max": 1, "rows": 3 },
            { "name": "BODY", "min": 0, "max": -1, "rows": 1 },
            { "name": "FOOTER",  "min": 1, "max": 1, "header": "^\s*总   计", "is_target": true,
                "columns": [
                    { "name": "transaction_count", "start_pos": 22, "length": 10 }
                ]
            }
        ]
    },
    "transform_declarations": {
        "FINAL_OUTPUT": { "object": {
            "transaction_count": { "xpath": "transaction_count" }
        }}
    }
}
```

However, then I realized there is a problem with this approach:

The first envelope is of fixed number of rows (3), that's easy.

The second part of your file has variable-length lines, that you don't care about. The issue, as I outlined in previous comments, is that if you use something like this:

```
{ "name": "BODY", "min": 0, "max": -1, "rows": 1 },
```

(where each line (rows = 1) is a record of the envelope, the record can repeat 0 or more or infinite times)

once the parser's state machine enters this envelope, it will never get out of this envelope, and it will swallow your last line in as a record of this envelope. So in essence, your last envelope (`FOOTER`) will never be reached.

#### Potential Solution

If let's say in your file, the middle section of the files don't have the word "总   计", then one solution would be:

```
        "envelopes" : [
            { "name": "HEADER", "min": 1, "max": 1, "rows": 3 },
            { "name": "BODY", "min": 0, "max": -1, "header": "^(?!.*总   计).+$" },
            { "name": "FOOTER",  "min": 1, "max": 1, "header": "^\s*总   计", "is_target": true,
                "columns": [
                    { "name": "transaction_count", "start_pos": 22, "length": 10 }
                ]
            }
        ]
```

Basically `BODY` envelope says let's inject all the lines that don't match the pattern `^(?!.*总   计).+$`. Unfortunately golang as far as I know, doesn't support negative lookahead regex. (Note, there might be some goalng native implementation of negative lookahead regex, but we're unwilling to switch golang native regex to those for such a small use case).

So instead, I prototyped and suggested this change:

```
            { "name": "BODY", "min": 0, "max": -1, "header": "^.*总   计.+$", "header_negative_match": true }
```

So introduction of `header_negative_match` to simulate negative match on a very coarse level. Of course this `header_negative_match` is by optional and by default is false, so no impact to any existing schema.

I'll create a branch for you to try it out soon. Let me know what you think?

**Comment by jf-tech** [comment]
@husthoper the branch for you to play around is: https://github.com/jf-tech/omniparser/tree/issue_219

You can check out the sample schema/input for reference: 
- [3_header_footer.schema.json](https://github.com/jf-tech/omniparser/blob/issue_219/extensions/omniv21/samples/fixedlength2/3_header_footer.schema.json)
- [3_header_footer.input.txt](https://github.com/jf-tech/omniparser/blob/issue_219/extensions/omniv21/samples/fixedlength2/3_header_footer.input.txt)

**Comment by jf-tech** [comment]
@husthoper If you're interested - we can consider adding this feature to support your use case. If not, we'll just wait until more needs arise.

**Comment by jf-tech** [comment]
@husthoper closing the ticket due to no updates/feedbacks from you. If you still need the feature, reopen the ticket and let us know.
