### ISSUE TITLE
Update goja Module

### ISSUE THREAD

**Issue by GordonFremen** [jf-tech/omniparser#221]
It'd be great if you could upgrade the version of goja to a more recent one. The current version in go.mod is ~4 years old.

My specific use case is that I'd like to be able to use ES6 features in JS custom functions. They have been [fully implemented](https://github.com/dop251/goja/milestone/1?closed=1).

I'd offer to do it but it's probably more work for you to deal with my PR!

**Comment by jf-tech** [comment]
@GordonFremen check the PR (https://github.com/jf-tech/omniparser/pull/222) and its commit branch (https://github.com/jf-tech/omniparser/pull/222/commits/810782f9bfe1b0cd82b713edba5441a03e74be81) for your own testing before we merge it to master and cut/tag a new release.

**Comment by GordonFremen** [comment]
@jf-tech Confirmed working, thank you!

**Comment by jf-tech** [comment]
[Release v1.0.5](https://github.com/jf-tech/omniparser/releases/tag/v1.0.5) has been cut.
